
server:
  port: 10004
spring:
  application:
    name: zhou-provider4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bmcar?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.joey.demo.pojo


