server:
  port: 10014
#datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmcar?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis  config
mybatis:

  mapper-locations: classpath:mapping/*.xml

  type-aliases-package: com.joey.demo.pojo
